services:
  # Redis cache/message broker
  - type: redis
    name: payout-redis
    ipAllowList: []
    plan: free

  # Web API
  - type: web
    name: payout-api
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DB_ENGINE
        value: postgresql
      - key: POSTGRES_DB
        fromDatabase:
          name: payout-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: payout-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: payout-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: payout-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: payout-db
          property: port
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: payout-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: payout-redis
          property: connectionString

  # Celery Worker
  - type: worker
    name: payout-worker
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && celery -A config worker -l info"
    envVars:
      - key: DB_ENGINE
        value: postgresql
      - key: POSTGRES_DB
        fromDatabase:
          name: payout-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: payout-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: payout-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: payout-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: payout-db
          property: port
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: payout-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: payout-redis
          property: connectionString

databases:
  - name: payout-db
    databaseName: payout_engine
    user: admin
