# Generated by Django 6.0.4 on 2026-04-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='merchant',
            name='country_code',
            field=models.CharField(default='IN', max_length=2),
        ),
    ]
