import axios from 'axios';

// For local testing, assuming the backend runs on localhost:8000
// and we have a valid token from seed_merchants.
const BASE_URL = 'http://localhost:8000/api/v1';

// For local testing, we use the token generated by `python manage.py seed_merchants`.
let AUTH_TOKEN = '14b5d28deb65a613cea091beaf7cdef6c3d2ec83'; 

export const setAuthToken = (token) => {
    AUTH_TOKEN = token;
    localStorage.setItem('auth_token', token);
}

const apiClient = axios.create({
    baseURL: BASE_URL,
    headers: {
        'Content-Type': 'application/json'
    }
});

apiClient.interceptors.request.use((config) => {
    if (AUTH_TOKEN) {
        config.headers['Authorization'] = `Token ${AUTH_TOKEN}`;
    }
    return config;
});

export const getMerchantProfile = async () => {
    const response = await apiClient.get('/merchants/me/');
    return response.data;
};

export const getLedger = async () => {
    const response = await apiClient.get('/merchants/me/ledger/');
    return response.data;
};

export const getPayouts = async () => {
    const response = await apiClient.get('/payouts/list/');
    return response.data;
};

export const createPayout = async (amount_paise, bank_account_id, idempotency_key) => {
    const response = await apiClient.post('/payouts/', {
        amount_paise,
        bank_account_id
    }, {
        headers: {
            'Idempotency-Key': idempotency_key
        }
    });
    return response.data;
};
