# Generated by Django 6.0.4 on 2026-04-30 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount_usd_cents', models.BigIntegerField()),
                ('tax_amount_usd_cents', models.BigIntegerField(default=0)),
                ('total_amount_usd_cents', models.BigIntegerField()),
                ('forex_rate_locked', models.DecimalField(decimal_places=4, max_digits=10)),
                ('platform_fee_usd_cents', models.BigIntegerField()),
                ('merchant_receives_inr_paise', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='merchants.merchant')),
            ],
        ),
    ]
